### ISSUE TITLE
O getTroco está retornando null, ou seja, não está devolvendo o troco ao cliente.

### ISSUE THREAD

**Issue by LacThales** [vihmar/Source-Code-Inspection#13]
![image](https://github.com/vihmar/Source-Code-Inspection/assets/63318165/079d0bbe-7590-4303-80bf-b0514c0a1445)

**Comment by vihmar** [comment]
<img width="264" alt="image" src="https://github.com/vihmar/Source-Code-Inspection/assets/65295232/b2d0c857-4a8c-4354-9ceb-e32a84a0ded6">

**Comment by vihmar** [comment]
#2
