### ISSUE TITLE
SaldoInsuficienteException vazia.

### ISSUE THREAD

**Issue by vihmar** [vihmar/Source-Code-Inspection#18]
![image](https://github.com/vihmar/Source-Code-Inspection/assets/65295232/70c825e0-ad4a-42d9-98e7-48cb90248f5f)

**Comment by LacThales** [comment]
![image](https://github.com/vihmar/Source-Code-Inspection/assets/63318165/eae3e9ca-5154-41a6-9fa4-9985b2fb8a19)
