### ISSUE TITLE
Classe TicketMachine está recebendo "valor" ao invés de "precoBilhete"

### ISSUE THREAD

**Issue by LacThales** [vihmar/Source-Code-Inspection#5]
![image](https://github.com/vihmar/Source-Code-Inspection/assets/63318165/1c0bf828-ba11-4882-bff6-b238fd5f6f3b)
![image](https://github.com/vihmar/Source-Code-Inspection/assets/63318165/f3454d56-6df6-44fb-a8cb-507dd522b4b6)

**Comment by vihmar** [comment]
<img width="271" alt="image" src="https://github.com/vihmar/Source-Code-Inspection/assets/65295232/fbf5dfa3-503e-4447-8297-05c961ba7d9a">

**Comment by vihmar** [comment]
#2
