### ISSUE TITLE
Dentro da função inserir está sempre acessando a posição "1" dentro da condição, sendo necessário que fosse "i".

### ISSUE THREAD

**Issue by LacThales** [vihmar/Source-Code-Inspection#8]
![image](https://github.com/vihmar/Source-Code-Inspection/assets/63318165/9b7ff9ca-322a-495c-b168-018f049da965)

**Comment by vihmar** [comment]
<img width="239" alt="image" src="https://github.com/vihmar/Source-Code-Inspection/assets/65295232/b7efd5f5-f129-458a-9aec-6ab5d5c15dde">

**Comment by vihmar** [comment]
#2
